---
# tasks file for deploy_docker
- name: Install Packages
  apt: name={{ packages }}

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present


- name: Update apt and install docker
  apt:  update_cache=yes name={{ docker }} state=latest
