---
# tasks file for deploy_metrics
- name: Install Packages
  apt: name={{ packages }}

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present


- name: Update apt and install docker
  apt:  update_cache=yes name={{ docker }} state=latest

  #- name: Create a directory for docker
  #  ansible.builtin.file:
  #    path: /root/docker
  #    state: directory
  #    mode: '0755'

- name: Add docker-compose files
  copy: src={{ item }} dest={{ docker_folder }} owner=root group=root mode=0755
  loop:
   - "docker"

- name: Add nginx config
  copy: src={{ item }} dest={{ nginx_folder }} owner=root group=root mode=0755
  loop:
   - "mon_server"

